spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/SB_AM
    username: root
    password: 
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
custom:
  file:
    dir: D:\cjh\upload
#server:
#  port: 8081
#  servlet:
#    context-path: /test